### ISSUE TITLE
OutOfMemoryError: CUDA out of memory

### ISSUE THREAD

**Issue by Khush-OGResearch** [Khush-OGResearch/videollm-online#1]
When I run the `python -m demo.app --resume_from_checkpoint chenjoya/videollm-online-8b-v1plus --attn_implementation sdpa` command got the following memory related error. What can be possible approaches to solve this

I am using NVIDIA GPU RTX 3050, NVIDIA-SMI 555.58.02, Driver Version: 555.58.02  and CUDA Version: 12.5, Available memory 4GB.

python -m demo.app --resume_from_checkpoint chenjoya/videollm-online-8b-v1plus --attn_implementation sdpa
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  9.00it/s]
!!! Set vision encoder in the model, only recommended for on in-the-wild inference. Please dont call this for efficient training & evaluation. Instead, do visual feature pre-extraction.
Traceback (most recent call last):
  File "/mnt/khush/khush_home/anaconda3/envs/myenv/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/khush/khush_home/anaconda3/envs/myenv/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/khush/khush_home/Downloads/videollm-online-main/demo/app.py", line 13, in <module>
    liveinfer = LiveInfer()
  File "/mnt/khush/khush_home/Downloads/videollm-online-main/demo/inference.py", line 16, in __init__
    self.model.to('cuda')
  File "/mnt/khush/khush_home/anaconda3/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1174, in to
    return self._apply(convert)
  File "/mnt/khush/khush_home/anaconda3/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/mnt/khush/khush_home/anaconda3/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/mnt/khush/khush_home/anaconda3/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  [Previous line repeated 5 more times]
  File "/mnt/khush/khush_home/anaconda3/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 805, in _apply
    param_applied = fn(param)
  File "/mnt/khush/khush_home/anaconda3/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1160, in convert
    return t.to(
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 112.00 MiB. GPU 0 has a total capacity of 3.72 GiB of which 57.06 MiB is free. Including non-PyTorch memory, this process has 3.17 GiB memory in use. Of the allocated memory 3.09 GiB is allocated by PyTorch, and 10.94 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by yusufali98** [comment]
Can you try the local CLI command from [here](https://github.com/showlab/videollm-online/tree/main?tab=readme-ov-file#quick-start) ?

**Comment by Khush-OGResearch** [comment]
**I checked running the command it shows:**

(myenv) khush@ogmen:~/Downloads/videollm-online-main$ python -m demo.app --resume_from_checkpoint chenjoya/videollm-online-8b-v1plus
Traceback (most recent call last):
  File "/mnt/khush/khush_home/anaconda3/envs/myenv/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/khush/khush_home/anaconda3/envs/myenv/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/khush/khush_home/Downloads/videollm-online-main/demo/app.py", line 13, in <module>
    liveinfer = LiveInfer()
  File "/mnt/khush/khush_home/Downloads/videollm-online-main/demo/inference.py", line 15, in __init__
    self.model, self.tokenizer = build_model_and_tokenizer(is_training=False, set_vision_inside=True, **asdict(args))
  File "/mnt/khush/khush_home/Downloads/videollm-online-main/models/live_llama/modeling_live_llama.py", line 73, in build_live_llama
    return build_live(config_class=LiveLlamaConfig, model_class=LiveLlamaForCausalLM, **kwargs)
  File "/mnt/khush/khush_home/Downloads/videollm-online-main/models/modeling_live.py", line 200, in build_live
    model = model_class.from_pretrained(llm_pretrained, config=config_class.from_pretrained(llm_pretrained, **kwargs), torch_dtype=torch_dtype, attn_implementation=attn_implementation)
  File "/mnt/khush/khush_home/anaconda3/envs/myenv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3826, in from_pretrained
    config = cls._autoset_attn_implementation(
  File "/mnt/khush/khush_home/anaconda3/envs/myenv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1556, in _autoset_attn_implementation
    cls._check_and_enable_flash_attn_2(
  File "/mnt/khush/khush_home/anaconda3/envs/myenv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1658, in _check_and_enable_flash_attn_2
    raise ImportError(f"{preface} the package flash_attn seems to be not installed. {install_message}")
ImportError: FlashAttention2 has been toggled on, but it cannot be used due to the following error: the package flash_attn seems to be not installed. Please refer to the documentation of https://huggingface.co/docs/transformers/perf_infer_gpu_one#flashattention-2 to install Flash Attention 2.

**So the problem is with flashattention:**
Collecting flash-attn==2.2.2
  Downloading flash_attn-2.2.2.tar.gz (2.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 12.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-qypx0ji8/flash-attn_c5aab1124eb64283a756897ebcba1d22/setup.py", line 110, in <module>
          raise RuntimeError("FlashAttention is only supported on CUDA 11.6 and above")
      RuntimeError: FlashAttention is only supported on CUDA 11.6 and above
      
      
      torch.__version__  = 2.4.1
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Khush-OGResearch** [comment]
When i did pip show flash-attn: WARNING: Package(s) not found: flash-attn

**Comment by yusufali98** [comment]
Can you install the `flash-attn` package then using pip ?

**Comment by Khush-OGResearch** [comment]
Sir now upgraded the system using UBUNTU 22.04, RTX 3080, Cuda-12.6, NVIDIA-Driver Version 560.35.03

Still getting the error with both the commands 
python -m demo.app --resume_from_checkpoint chenjoya/videollm-online-8b-v1plus

videollm-online) ogmen@ogmen-Alienware-Aurora-R13:~/Ogmen_Research/videollm-online-main$ python -m demo.app --resume_from_checkpoint chenjoya/videollm-online-8b-v1plus
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 15.20it/s]
!!! Set vision encoder in the model, only recommended for on in-the-wild inference. Please dont call this for efficient training & evaluation. Instead, do visual feature pre-extraction.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ogmen/Ogmen_Research/videollm-online-main/demo/app.py", line 13, in <module>
    liveinfer = LiveInfer()
                ^^^^^^^^^^^
  File "/home/ogmen/Ogmen_Research/videollm-online-main/demo/inference.py", line 16, in __init__
    self.model.to('cuda')
  File "/home/ogmen/miniconda3/envs/videollm-online/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1174, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ogmen/miniconda3/envs/videollm-online/lib/python3.11/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/home/ogmen/miniconda3/envs/videollm-online/lib/python3.11/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/home/ogmen/miniconda3/envs/videollm-online/lib/python3.11/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  [Previous line repeated 5 more times]
  File "/home/ogmen/miniconda3/envs/videollm-online/lib/python3.11/site-packages/torch/nn/modules/module.py", line 805, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/home/ogmen/miniconda3/envs/videollm-online/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1160, in convert
    return t.to(
           ^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 32.00 MiB. GPU 0 has a total capacity of 9.67 GiB of which 22.06 MiB is free. Including non-PyTorch memory, this process has 9.21 GiB memory in use. Of the allocated memory 8.99 GiB is allocated by PyTorch, and 9.71 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

------------------------------------------------------------------------------------------------------------------------------------------------

python -m demo.cli --resume_from_checkpoint chenjoya/videollm-online-8b-v1plus

(videollm-online) ogmen@ogmen-Alienware-Aurora-R13:~/Ogmen_Research/videollm-online-main$ python -m demo.cli --resume_from_checkpoint chenjoya/videollm-online-8b-v1plus
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 20.90it/s]
!!! Set vision encoder in the model, only recommended for on in-the-wild inference. Please dont call this for efficient training & evaluation. Instead, do visual feature pre-extraction.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ogmen/Ogmen_Research/videollm-online-main/demo/cli.py", line 53, in <module>
    liveinfer = LiveInfer()
                ^^^^^^^^^^^
  File "/home/ogmen/Ogmen_Research/videollm-online-main/demo/inference.py", line 16, in __init__
    self.model.to('cuda')
  File "/home/ogmen/miniconda3/envs/videollm-online/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1174, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ogmen/miniconda3/envs/videollm-online/lib/python3.11/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/home/ogmen/miniconda3/envs/videollm-online/lib/python3.11/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/home/ogmen/miniconda3/envs/videollm-online/lib/python3.11/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  [Previous line repeated 5 more times]
  File "/home/ogmen/miniconda3/envs/videollm-online/lib/python3.11/site-packages/torch/nn/modules/module.py", line 805, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/home/ogmen/miniconda3/envs/videollm-online/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1160, in convert
    return t.to(
           ^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 32.00 MiB. GPU 0 has a total capacity of 9.67 GiB of which 19.06 MiB is free. Including non-PyTorch memory, this process has 9.21 GiB memory in use. Of the allocated memory 8.99 GiB is allocated by PyTorch, and 9.71 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by yusufali98** [comment]
Can you replace [this line](https://github.com/Khush-OGResearch/videollm-online/blob/main/models/modeling_live.py#L200) with something like the following:

```
    # Configure 4-bit quantization parameters
    bnb_4bit_compute_dtype = torch.float16
    bnb_4bit_use_double_quant = True
    bnb_4bit_quant_type = "nf4"

    # Load model with 4-bit precision
    model = model_class.from_pretrained(
        llm_pretrained,
        config=config_class.from_pretrained(llm_pretrained, **kwargs),
        torch_dtype=torch_dtype,
        attn_implementation=attn_implementation,
        load_in_4bit=load_in_4bit,
        bnb_4bit_compute_dtype=bnb_4bit_compute_dtype,
        bnb_4bit_use_double_quant=bnb_4bit_use_double_quant,
        bnb_4bit_quant_type=bnb_4bit_quant_type
    )
```

I am not sure if the above will work exactly but the basic idea is to convert the model explicitly to 4-bit precision to redcue the CUDA memory usage. You also need to install the `bitsnbytes` package with `pip install bitsandbytes`
and also need to import in the above script with `import bitsandbytes as bnb`
