### ISSUE TITLE
Error During Video Inference in videollm-online: Flash Attention GPU Initialization and Win32 Application Error

### ISSUE THREAD

**Issue by Khush-OGResearch** [Khush-OGResearch/videollm-online#2]
Please check everything is setup properly while inferencing the app is able to start and when video is inputted it throws the following error, kindly please guide me. So when I run the app code at that time the local host were started and when i uploaded the video and sent a message it was not able to give the answer (please see attached figure). Here Video Backend is changed from the video_reader to pyav as video_reader only supports the Linux or it was not working that's why based on [this](https://github.com/pytorch/vision#installation).

![Screenshot 2024-10-03 194644](https://github.com/user-attachments/assets/0024760c-1ce4-4d93-971b-a32a0cd82842)

(videollm-online) C:\Ogmen-Research\videollm-online-main>python -m demo.app --resume_from_checkpoint chenjoya/videollm-online-8b-v1plus
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  4.02it/s]
!!! Set vision encoder in the model, only recommended for on in-the-wild inference. Please dont call this for efficient training & evaluation. Instead, do visual feature pre-extraction.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Traceback (most recent call last):
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\anyio\_backends\_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\anyio\_backends\_asyncio.py", line 914, in run
    result = context.run(func, *args)
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "C:\Ogmen-Research\videollm-online-main\demo\app.py", line 67, in gr_video_change
    ffmpeg_once(src_video_path, ffmpeg_video_path, fps=liveinfer.frame_fps, resolution=liveinfer.frame_resolution)
  File "C:\Ogmen-Research\videollm-online-main\data\utils.py", line 66, in ffmpeg_once
    subprocess.run(command, check=True)
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application
Traceback (most recent call last):
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\anyio\_backends\_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\anyio\_backends\_asyncio.py", line 914, in run
    result = context.run(func, *args)
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "C:\Ogmen-Research\videollm-online-main\demo\app.py", line 67, in gr_video_change
    ffmpeg_once(src_video_path, ffmpeg_video_path, fps=liveinfer.frame_fps, resolution=liveinfer.frame_resolution)
  File "C:\Ogmen-Research\videollm-online-main\data\utils.py", line 66, in ffmpeg_once
    subprocess.run(command, check=True)
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application
Traceback (most recent call last):
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\anyio\_backends\_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\anyio\_backends\_asyncio.py", line 914, in run
    result = context.run(func, *args)
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "C:\Ogmen-Research\videollm-online-main\demo\app.py", line 63, in gr_video_change
    name, ext = os.path.splitext(src_video_path)
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\ntpath.py", line 230, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\anyio\_backends\_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\anyio\_backends\_asyncio.py", line 914, in run
    result = context.run(func, *args)
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "C:\Ogmen-Research\videollm-online-main\demo\app.py", line 67, in gr_video_change
    ffmpeg_once(src_video_path, ffmpeg_video_path, fps=liveinfer.frame_fps, resolution=liveinfer.frame_resolution)
  File "C:\Ogmen-Research\videollm-online-main\data\utils.py", line 66, in ffmpeg_once
    subprocess.run(command, check=True)
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by Khush-OGResearch** [comment]
With CLI

(videollm-online) C:\Ogmen-Research\videollm-online-main>python -m demo.cli --resume_from_checkpoint chenjoya/videollm-online-8b-v1plus
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  3.36it/s]
!!! Set vision encoder in the model, only recommended for on in-the-wild inference. Please dont call this for efficient training & evaluation. Instead, do visual feature pre-extraction.
Traceback (most recent call last):
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Ogmen-Research\videollm-online-main\demo\cli.py", line 54, in <module>
    main(liveinfer)
  File "C:\Ogmen-Research\videollm-online-main\demo\cli.py", line 19, in main
    ffmpeg_once(src_video_path, ffmpeg_video_path, fps=liveinfer.frame_fps, resolution=liveinfer.frame_resolution)
  File "C:\Ogmen-Research\videollm-online-main\data\utils.py", line 66, in ffmpeg_once
    subprocess.run(command, check=True)
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\divye\miniconda3\envs\videollm-online\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application
